### ISSUE TITLE
F0AKF subsroutine in CGEIG.FOR

### ISSUE THREAD

**Issue by Recaedae** [fjargsto/AcousticBEM#16]
NAG seems to have replaced the F02AKF subroutine in CGEIG.FOR. Can you please tell me how you managed to replace it. I am struggling with the math concerned with the eigenvectors and eigenvalues calculations. Thank you.

**Comment by fjargsto** [comment]
I don't think I ever got the Fortran code that was using the Eigenvector stuff to work (the examples that compute the resonances inside an enclosed volume). I did have to replace another NAG function and if I recall correctly, I used a Gnu numerical library which had Fortran bindings.
